### ISSUE TITLE
Add configuration details to HTML report?

### ISSUE THREAD

**Issue by karfau** [stryker-mutator/stryker-js#2301]
**Is your feature request related to a problem? Please describe.**
Yesterday evening I was able to produce a stryker report with an awesomly high score and it took close to an hour to run. I only remember that I used the `command` runner and that I had less test suites configured.

To improve performance I switched to jest and had many iterations until it worked, but only with a much lower resulting score (and many timeouts and runtime errors, but that's a topic for a different issue).

I still have that report open in a tab in my browser, but it's no longer on the disk.

So far I was not able to get back to my old configuration (I know, should have commited that, but I didn't...)

**Describe the solution you'd like**
If (at least) the configuration that was used (and ideally a list of the files that have been copied into the sandbox at that point in time) would be available from the HTML report, it would also be more easy to reproduce that report for others looking at it (or verify it was produced with what is in the repo, if needed).
There are many more ideas for information in the report:
- OS and stryker/test runner versions
- duration it took to generate the report
- final result of test runner config (e.g. the resulting jest config that was actually applied after merging the many options)
But I think the config file/object would be the most valuable to be able to reproduce the report.

**Describe alternatives you've considered**
I will try to use the "Local history" feature of my IDE to recover the config, and for sure commit such beautiful setups into git in the future...

**Additional context**
Maybe this becomes less of an issue with the reduced amount of time it takes to produce a report soon, but it would still add transparency to a report, especially with the possible complexity of tools invoked.

**Comment by karfau** [comment]
It surprises me that there is no feedback on this feature request at all.

Is it more because you think that it's not worth investing time, or because you think it's hard to do?

**Comment by nicojs** [comment]
Hi @karfau 

> Is it more because you think that it's not worth investing time, or because you think it's hard to do?

Neither. We are an open-source project and thus have limited time to invest in issues and features. Sometimes it happens that an issue is reported and goes unnoticed. That seems to have happened here, I'm sorry about that. We're not bad people, sorry.

On the bright side: I think we've already implemented this feature... sort of. StrykerJS will add your config to the mutation testing report, but it is currently not yet displayed in the HTML report.

StrykerJS uses the [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements/), in which we recently added the ability to add configuration to the json report:
https://github.com/stryker-mutator/mutation-testing-elements/blob/e434aa9b1c56d90058396423a22bfe75300a8ab2/packages/report-schema/src/mutation-testing-report-schema.json#L9-L12

Since StrykerJS@5.0.0, this `"config"` property is filled with the config object. The easiest way to see it is to use the `"json"` reporter, but you could also look in the source of the HTML reporter and search for `"config"`.

We're planning to add it visually to the HTML report, if you have some ideas about that, please feel free to [open an issue there](https://github.com/stryker-mutator/mutation-testing-elements/issues/new).

**Comment by karfau** [comment]
Thanks for the update. 
Although it doesn't solve the problem for the report that I used, since it was created by v4, I think anything relevant will happen in the new issue I created, so I'll close this one.
